module.exports = [
	{"name": "Castle", "icon": "fa-solid fa-chess-rook"},
	{"name": "Top of the world", "icon": "fa-solid fa-mountain"},
	{"name": "Beach", "icon": "fa-solid fa-umbrella-beach"},
	{"name": "Lighthouse", "icon": "fa-solid fa-tower-observation"},
	{"name": "OMG!", "icon": "fa-solid  fa-space-awesome"},
	{"name": "Ocean", "icon": "fa-solid fa-person-swimming"},
	{"name": "Amazing pool", "icon": "fa-solid fa-water-ladder"},
	{"name": "Lakefront", "icon": "fa-solid fa-house-flood-water"},
	{"name": "Farm", "icon": "fa-solid fa-tractor"},
	{"name": "Beachfront", "icon": "fa-solid fa-umbrella-beach"},
	{"name": "Camper vans", "icon": "fa-solid fa-caravan"},
	{"name": "Rooms", "icon": "fa-solid fa-bed"},
	{"name": "A frame", "icon": "fa-solid fa-a"},
	{"name": "Arctic", "icon": "fa-solid fa-snowflake"},
	{"name": "Trending", "icon": "fa-solid fa-fire"},
	{"name": "Garden", "icon": "fa-solid fa-clover"},
	{"name": "Cabin", "icon": "fa-solid fa-warehouse"},
	{"name": "Mordern", "icon": "fa-solid fa-hotel"},
	{"name": "Apartment", "icon": "fa-solid fa-building"},
	{"name": "Nature", "icon": "fa-solid fa-seedling"},
	{"name": "Couple", "icon": "fa-solid fa-children"},
];
